### PR TITLE
fixing two XML files

### PR DESCRIPTION
**Pull request by arademaker**
This is a sample of fix... if you agree, I can send a new PR solving all validation issues.

### CODE REVIEW

**Comment by arademaker** [comment]
all XML files in `verbnet3.4` folder are now XML valid according to the vn_class-3.dtd. is this folder in sync with the web interface https://uvi.colorado.edu/uvi_search?

**Comment by ghamzak** [comment]
Thank you for the fixes. 
Not yet. There has been a recent batch of change to the xml files which is not yet pulled in the UVI repo.

**Comment by arademaker** [comment]
Thank you, but can we consider the files here the most recent VERBNET?

**Comment by ghamzak** [comment]
Yes, you can.

**Pull request merged**
